/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.galvanize;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String name = "World";
        if (args.length == 1) {
            name = args[0];
        }

        System.out.println("Hello "+name+" !!!");
    }
}
